# Generated by Django 4.1.3 on 2022-11-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("degree_courses", models.CharField(max_length=100)),
                ("type_of_field3", models.CharField(max_length=100)),
                ("course_code", models.CharField(max_length=100)),
                ("course_title", models.CharField(max_length=100)),
                ("course_title_english", models.CharField(max_length=100)),
                ("instructor", models.CharField(max_length=100)),
                ("campus", models.CharField(max_length=100)),
                ("type_of_field2", models.CharField(max_length=100)),
                ("credit", models.CharField(max_length=100)),
                ("classtime", models.CharField(max_length=100)),
                ("type_of_class1", models.CharField(max_length=100)),
                ("type_of_class2", models.CharField(max_length=100)),
                ("remarks", models.CharField(max_length=100)),
                ("major", models.CharField(max_length=100)),
                ("semester", models.CharField(max_length=100)),
                ("college", models.CharField(max_length=100)),
            ],
        ),
    ]
