# Generated by Django 4.1.3 on 2022-11-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skku", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="campus",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="classtime",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="college",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="course_title",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="course_title_english",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="credit",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="degree_courses",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="instructor",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="major",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="remarks",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="semester",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="type_of_class1",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="type_of_class2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="type_of_field2",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="type_of_field3",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="subject",
            unique_together={("course_code", "semester")},
        ),
    ]
