# Generated by Django 4.1.3 on 2022-11-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skku", "0003_alter_subject_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="classtime",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="course_title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="course_title_english",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="credit",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="semester",
            field=models.CharField(max_length=100),
        ),
    ]
