# Generated by Django 4.1.3 on 2022-11-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skku", "0004_alter_subject_classtime_alter_subject_course_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subject",
            name="id",
        ),
        migrations.AddField(
            model_name="subject",
            name="course_id",
            field=models.AutoField( primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
