# Generated by Django 4.1.3 on 2022-11-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("student_id", models.IntegerField(primary_key=True, serialize=False)),
                ("major", models.CharField(max_length=100)),
                ("double_major", models.CharField(max_length=100)),
                ("triple_major", models.CharField(max_length=100)),
            ],
        ),
    ]
