# Generated by Django 4.1.3 on 2022-11-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Student",
            new_name="Academic",
        ),
    ]
