# Generated by Django 4.1.3 on 2022-11-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_rename_student_academic"),
    ]

    operations = [
        migrations.AddField(
            model_name="academic",
            name="student_name",
            field=models.CharField(default="홍길동", max_length=50),
        ),
    ]
