# Generated by Django 4.1.3 on 2022-11-04 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_academic_double_major_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instructor", models.CharField(max_length=50)),
                ("morningclass", models.BooleanField()),
                ("courseRatio", models.FloatField()),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.academic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mandatory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=50)),
                ("credit", models.IntegerField()),
                ("time", models.CharField(max_length=50)),
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.academic",
                    ),
                ),
            ],
        ),
    ]
