# Generated by Django 4.1.3 on 2022-11-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0005_preference_mandatory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mandatory",
            name="id",
        ),
        migrations.RemoveField(
            model_name="preference",
            name="id",
        ),
        migrations.AlterField(
            model_name="mandatory",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="student.academic",
            ),
        ),
        migrations.AlterField(
            model_name="preference",
            name="student_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="student.academic",
            ),
        ),
    ]
