# Generated by Django 4.1.3 on 2022-11-15 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skku", "0001_initial"),
        ("student", "0006_remove_mandatory_id_remove_preference_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="student.academic",
                    ),
                ),
                (
                    "course_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student.Timetable.course_code+",
                        to="skku.subject",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student.Timetable.semester+",
                        to="skku.subject",
                    ),
                ),
            ],
        ),
    ]
