# Generated by Django 4.1.3 on 2022-11-16 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skku", "0003_alter_subject_unique_together"),
        ("student", "0007_timetable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timetable",
            name="semester",
        ),
        migrations.AddField(
            model_name="timetable",
            name="trial",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="student.academic",
                    ),
                ),
                (
                    "course_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student.History.course_code+",
                        to="skku.subject",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student.History.semester+",
                        to="skku.subject",
                    ),
                ),
            ],
        ),
    ]
