# Generated by Django 4.1.3 on 2022-11-17 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skku", "0005_remove_subject_id_subject_course_id"),
        ("student", "0009_remove_timetable_course_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("semester", models.CharField(max_length=50)),
                (
                    "course_id",
                    models.ForeignKey(
                        db_column="course_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skku.subject",
                    ),
                ),
                (
                    "student_id",
                    models.ForeignKey(
                        db_column="student_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student.academic",
                    ),
                ),
            ],
        ),
    ]
