# Generated by Django 4.1.3 on 2022-11-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0010_history"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="instructor",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
