# Generated by Django 4.1.3 on 2022-11-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0011_alter_preference_instructor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatory",
            name="course",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
