# Generated by Django 4.1.3 on 2022-11-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0012_alter_mandatory_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatory",
            name="time",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
