# Generated by Django 4.1.3 on 2022-11-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0013_alter_mandatory_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandatory",
            name="five_days_a_week",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
