# Generated by Django 4.1.3 on 2022-11-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0014_mandatory_five_days_a_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preference",
            name="onlinePreference",
            field=models.BooleanField(null=True),
        ),
    ]
