# Generated by Django 4.1.3 on 2022-11-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0015_alter_preference_onlinepreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatory",
            name="five_days_a_week",
            field=models.IntegerField(null=True),
        ),
    ]
