# Generated by Django 4.1.3 on 2022-11-27 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0016_alter_mandatory_five_days_a_week"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preference",
            name="onlinePreference",
        ),
    ]
