# Generated by Django 4.1.3 on 2022-11-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="major",
            unique_together={("course_code", "semester", "major")},
        ),
    ]
