# Generated by Django 4.1.3 on 2022-11-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0006_remove_mandatory_id_remove_preference_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "student_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="student.academic",
                        unique=True,
                    ),
                ),
                ("login_id", models.CharField(max_length=20)),
                ("login_password", models.CharField(max_length=20)),
            ],
        ),
    ]
