# Generated by Django 4.1.3 on 2022-11-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0007_timetable"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Info",
        ),
    ]
